# Generated by Django 5.2.10 on 2026-03-15 15:41

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoReelPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("narration", "Narration"),
                            ("character", "Animation / Character"),
                            ("audiobook", "Audiobook"),
                            ("elearning", "E-Learning"),
                            ("promo", "Promo"),
                            ("other", "Other"),
                        ],
                        default="commercial",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Upload an audio file (MP3, WAV, or OGG). Max 50 MB.",
                        upload_to="demos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg"]
                            )
                        ],
                    ),
                ),
                ("description", wagtail.fields.RichTextField(blank=True)),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        help_text='Duration display (e.g., "1:30")',
                        max_length=10,
                    ),
                ),
                (
                    "transcript",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Optional transcript of the demo reel."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PortfolioIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("rich_text", 0), ("image", 1), ("video", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.RichTextBlock", (), {}),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Paste a YouTube or Vimeo URL"},
                            ),
                        },
                    ),
                ),
                (
                    "credentials",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Training, certifications, and credentials.",
                    ),
                ),
                (
                    "profile_photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile photo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="PortfolioHeadshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("caption", models.CharField(blank=True, max_length=250)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headshots",
                        to="portfolio.portfolioindexpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
