# Generated by Django 5.2.15 on 2026-07-07 12:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_configure_wagtail_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', 0), ('image', 1), ('video', 2)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'template': 'blog/blocks/image_block.html'}), 2: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste a YouTube or Vimeo URL'})}),
        ),
    ]
